services:
  envoy:
    image: envoyproxy/envoy:v1.29.0
    ports:
      - "8081:8080"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: host
    depends_on:
      - server

  server:
    build:
      context: ./example/server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
