[workspace]
members = ["example/types", "example/server", "example/client"]

[package]
name = "grpc-web-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
] }
prost = "0.13"
bytes = "1"
futures = "0.3"
pin-project = "1"
anyhow = "1"
thiserror = "2"
base64 = "0.22"

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "s"
lto = true
