// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CountRequest {
    #[prost(int32, tag = "1")]
    pub start: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CountResponse {
    #[prost(int32, tag = "1")]
    pub value: i32,
}
